routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\SpecializationController;
use App\Http\Controllers\Admin\DoctorController;
use App\Http\Controllers\Admin\AppointmentController;
use App\Http\Controllers\Frontend\SpecializationController as FrontendSpecializationController;
use App\Http\Controllers\Frontend\DoctorController as FrontendDoctorController;
use App\Http\Controllers\Frontend\AppointmentController as FrontendAppointmentController;
use App\Http\Controllers\Frontend\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('front-specializations', [FrontendSpecializationController::class, 'index'])->name('front.specializations.index');
Route::get('front-specializations/{specialization}', [FrontEndSpecializationController::class, 'show'])->name('front.specializations.show');
Route::get('front-doctors', [FrontendDoctorController::class, 'index'])->name('front.doctors.index');
Route::get('/appointments/appForm/step-one', [FrontEndAppointmentController::class, 'appFormStepOne'])->name('appointments.appForm.step.one');
Route::post('/appointments/appForm/step-one',[FrontEndAppointmentController::class,'storeAppFormStepOne'])->name('appointments.storeAppForm.step.one');
Route::get('/appointments/appForm/step-two', [FrontEndAppointmentController::class, 'appFormStepTwo'])->name('appointments.appForm.step.two');
Route::post('/appointments/appForm/step-two',[FrontEndAppointmentController::class,'storeAppFormStepTwo'])->name('appointments.storeAppForm.step.two');
Route::get('/thankyou', [WelcomeController::class, 'thankyou'])->name('thankyou');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth','admin'])->name('admin.')->group(function() {
    Route::get('/admin', [AdminController::class, 'AdminDashboard'])->name('dashboard');
    Route::get('/admin/logout', [AdminController::class, 'AdminLogout'])->name('logout');
    Route::get('/admin/profile', [AdminController::class, 'AdminProfile'])->name('profile');
    Route::post('/admin/profile/store', [AdminController::class, 'AdminProfileStore'])->name('profile.store');
    Route::get('/admin/change/password', [AdminController::class, 'AdminChangePassword'])->name('change.password');
    Route::post('/admin/password/update', [AdminController::class, 'AdminPasswordUpdate'])->name('password.update');
    
});
    
Route::middleware(['auth','admin'])->group(function() {

    //routes for specialization
    Route::get('/specializations', [SpecializationController::class,'showSpecializations'])->name('showSpecializations');
    Route::post('specializations/store', [SpecializationController::class,'addSpecialization']);
    Route::get('specializations/{specialization}/edit', [SpecializationController::class,'editSpecialization']);
    Route::put('specializations/{specialization}/update', [SpecializationController::class,'updateSpecialization']);
    Route::delete('specializations/destroy/{specialization}', [SpecializationController::class,'deleteSpecialization']);
    
    //routes for doctor
    Route::get('/doctors',  [DoctorController::class,'index'])->name('doctors.index');
    Route::post('/store', [DoctorController::class, 'store'])->name('doctors.store');
    Route::get('/fetchall', [DoctorController::class, 'fetchAll'])->name('doctors.fetchall');
    Route::delete('/destroy', [DoctorController::class, 'destroy'])->name('doctors.delete');
    Route::get('/edit', [DoctorController::class, 'edit'])->name('doctors.edit');
    Route::post('/update', [DoctorController::class, 'update'])->name('doctors.update'); 
    
    //routes for appointments
    Route::get('/appointments', [AppointmentController::class, 'index'])->name('appointments.index');
    Route::get('/appointments/create', [AppointmentController::class, 'create'])->name('appointments.create');
    Route::post('/appointments/store', [AppointmentController::class, 'store'])->name('appointments.store');
    Route::get('/appointments/edit/{appointment}', [AppointmentController::class, 'edit'])->name('appointments.edit');
    Route::put('/appointments/update/{appointment}', [AppointmentController::class, 'update'])->name('appointments.update');
    Route::delete('/appointments/delete/{appointment}', [AppointmentController::class, 'destroy'])->name('appointments.delete');

});



require __DIR__.'/auth.php';

app/Models/Specialization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Specialization extends Model
{
    use HasFactory;
    
    protected $guarded = [];

    public function doctors(){
        return $this->hasMany(Doctor::class);
    }
}

app/Http/Controllers/Admin/SpecializationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Specialization;
use Illuminate\Support\Facades\Validator;


class SpecializationController extends Controller
{
    
    public function showSpecializations(){
      
        $specializations = Specialization::all();        
        return view('backend.specialization.index', compact('specializations'));
    }



    public function addSpecialization(Request $request){

        $validator = Validator::make($request->all(), [
            'specialization_name' => 'required',
        ],
        [
            'specialization_name.required' => 'Please enter specialization name',    
        ]);

        if ($validator->fails()) {
            return response()->json([
                        'error' => $validator->errors()->all()
                    ]);
        }        
        else{
            $specialization = Specialization::updateOrCreate(          
                ['id' => $request->id],
                ['specialization_name' => $request->specialization_name, 
                'specialization_slug' => strtolower(str_replace(' ','-', $request->specialization_name))
                ]);
        }

        $arr = array($specialization, 'msg' => 'Successfully Specialization Submit', 'status' => true);
        return response()->json($arr);
    }

    

   public function editSpecialization(Specialization $specialization){
       
        return response()->json($specialization);
    }

    public function deleteSpecialization(Specialization $specialization){
        $specialization->delete();
        return response()->json('success');
    }

}

app/Http/Controllers/Frontend/SpecializationController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Doctor;
use App\Models\Specialization;

class SpecializationController extends Controller
{
    public function index(){
        $specializations = Specialization::all();
        return view('specializations.index', compact('specializations'));
    }
    
    public function show(Specialization $specialization){
        //$doctors = Doctor::where('status', DoctorStatus::Available)->get();
        return view('specializations.show', compact('specialization'));
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/specializations/index.blade.php
<x-guest-layout>    
    <div class="md:flex md:flex-wrap mt-24 text-center md:-mx-4">        
        @foreach($specializations as $specialization)
            <div class="md:w-1/2 md:px-4 lg:w-2/2">
                <div class="bg-white rounded-lg border border-gray-300 p-8">
                    <img src="{{asset('frontend/images/clinic-plus-logo.png')}}" alt="" class="h-20 mx-auto">
                    <h4 class="text-xl font-bold mt-4">{{ $specialization->specialization_name }}</h4>                
                    <a href="{{ route('front.specializations.show', $specialization->id) }}" class="block mt-4">Show Doctors</a>
                </div>
            </div>
        @endforeach
    </div>        
</x-guest-layout>

resources/views/specializations/show.blade.php
<x-guest-layout>
    <div class="container w-full px-5 py-6 mx-auto">
        <br><br><br><br><br><br><br><br>
        <div class="grid lg:grid-cols-4 gap-y-6">
            @foreach ($specialization->doctors as $doctor)
                <div class="bg-white rounded-lg border border-gray-300 p-8">
                    <img class="h-48 mx-auto rounded" src="{{asset('storage/doctors/'.$doctor->image)}}" alt="Image" loading="lazy"/>
                    <div class="px-6 py-4 text-center">
                        <h4 class="mb-3 text-xl font-semibold tracking-tight text-green-600 uppercase">
                            Dr.{{ $doctor->full_name }}</h4>
                        <p class="leading-normal text-gray-700 text-center">
                            {{ $doctor->professional_statement }}
                        </p>
                        <p>
                            <span class="text-l text-green-600">Appointment price: ${{ $doctor->app_price }}</span>
                        </p>    
                    </div>
                    <div class="flex items-center justify-between p-2">
                        <a href="{{route('appointments.appForm')}}" class="px-2 py-2 bg-teal-500 text-white rounded inline-block mt-8 font-semibold mx-auto">Make
                            Appointment</a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</x-guest-layout>    